server:
  port: 8088
  servlet:
    context-path: /unit-testing
spring:
  application:
    name: unittesting
  datasource:
    url: jdbc:h2:mem:unittestdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect